title: Digitando Blog
email: lucassilvacds7@gmail.com
description: Feito com jekyllrb.
baseurl: "/blog"
url: "https://luccasscds.github.io"

# Social networds
linkedin_username: lucassilva21
github_username:  luccasscds

# Link posts
permalink: /post/:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed