title: Digitando blog
tagline: Blog focando em compartilhar conhecimentos para programadores
logo: /assets/images/logo.png
description: jekyllrb
url: "https://luccasscds.github.io"
baseurl: "/blog"
locale: pt

# Social networds
linkedin_username: lucassilva21
github_username:  luccasscds
instagram_username: programadorlucas

# authors
collections:
  authors:
    output: true

# Link posts
permalink: /:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag