title: Digitando blog
logourl: /assets/images/logo.png
email: ""
description: Feito com jekyllrb.
baseurl: "/blog"
url: "https://luccasscds.github.io"

# Social networds
linkedin_username: lucassilva21
github_username:  luccasscds
instagram_username: programadorlucas

# Link posts
permalink: /post/:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed