title: Digitando blog
logourl: /assets/images/logo.png
email: ""
description: jekyllrb
baseurl: "/blog"
url: "https://luccasscds.github.io"

# Social networds
linkedin_username: lucassilva21
github_username:  luccasscds
instagram_username: programadorlucas

# Link posts
permalink: /:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag